#!/usr/bin/env python3
"""Generate site/clauses.js from compact.md + ledgers/law-table.md.

Run after every change to the body or the law table:
    python3 tools/gen_site_data.py

The site's clause explorer renders this data; hand-editing site/clauses.js
is pointless (it is overwritten) and editing the body without regenerating
desyncs the explorer. A future build gate should run this + `git diff --exit-code site/clauses.js`.
"""
import re, json, sys

BODY = 'compact.md'
LAW  = 'ledgers/law-table.md'
OUT  = 'site/clauses.js'

text = open(BODY).read()

# ---- parts ----
parts = []  # {id, title, trigger(optional), force_kind}
part_re = re.compile(r'^## (Part [IVX]+) — (.+)$', re.M)
cap_re = re.compile(r'^### ([A-Z]+) — (.+?) · (\[[^\]]+\])$', re.M)
for m in part_re.finditer(text):
    parts.append({'id': m.group(1), 'title': m.group(2).strip(), 'trigger': None})
cap_parts = []
for m in cap_re.finditer(text):
    pid, name, tag = m.group(1), m.group(2).strip(), m.group(3)
    trigger = re.search(r'C:\s*(.+?)\]', tag)
    cap_parts.append({'id': pid, 'title': name, 'trigger': trigger.group(1).strip() if trigger else tag.strip()})

# ---- clauses ----
clause_re = re.compile(r'^\*\*([A-Z]{1,3}-\d+) · (\[[^\]]+\]) · (?:\(core\) · )?([^.]+?)\.?\*\*\s*(.*)$', re.M)
clauses = []
cur_part = 'Part I'
lines = text.splitlines()
# map line numbers -> part
part_bounds = [(text[:m.start()].count('\n')+1, m.group(1)) for m in part_re.finditer(text)]
def part_of(lineno):
    p = 'Part I'
    for ln, pid in part_bounds:
        if ln <= lineno: p = pid
    return p

matches = list(clause_re.finditer(text))
for i, m in enumerate(matches):
    cid, force, title, first = m.group(1), m.group(2), m.group(3).strip(), m.group(4)
    start = m.end()
    end = matches[i+1].start() if i+1 < len(matches) else len(text)
    seg = text[start:end]
    seg = seg.split('\n---')[0]
    # stop only at real headers (a wrapped line may open with **bold**)
    for stop in ['\n## ', '\n### ', '\n**[', '\n**A-', '\n**C', '\n**D-', '\n**F-', '\n**I-', '\n**J-', '\n**M', '\n**R-']:
        idx = seg.find(stop)
        if idx != -1: seg = seg[:idx]
    body_text = re.sub(r'[`*]', '', re.sub(r'\s+', ' ', seg)).strip()
    core = '(core)' in m.group(0)[:60]
    within = re.search(r'\[M within ([A-Z]+)\]', force)
    clauses.append({
        'id': cid,
        'part': part_of(text[:m.start()].count('\n')+1),
        'force': 'M' if force.startswith('[M') else ('C' if force.startswith('[C') else 'O'),
        'within': within.group(1) if within else None,
        'core': core,
        'title': title.rstrip('.'),
        'text': body_text,
    })

# ---- law table incidence ----
law = {}
lt = open(LAW).read()
for lm in re.finditer(r'^\| `([A-Z]{1,3}-\d+)` \| (.+?) \| (.+?) \| (.+?) \| (.+?) \| (.+?) \|$', lt, re.M):
    cid, bound, invoker, against, mech, dsh = [x.strip() for x in lm.groups()]
    law[cid] = {'bound': bound, 'invoker': invoker, 'against': against, 'mechanism': mech, 'dsh': dsh}

for c in clauses:
    c['inc'] = law.get(c['id'])

missing = [c['id'] for c in clauses if c['id'] not in law]
extra = [k for k in law if k not in {c['id'] for c in clauses}]
if missing: print('WARN: clauses without law-table row:', missing)
if extra: print('WARN: law-table rows without clause:', extra)

data = {'source': {'body': 'compact.md', 'law_table': 'ledgers/law-table.md'},
        'parts': parts, 'cap_parts': cap_parts, 'clauses': clauses}
out = '/* GENERATED by tools/gen_site_data.py — do not edit. Regenerate: python3 tools/gen_site_data.py */\n'
out += 'window.COMPACT_DATA = ' + json.dumps(data, ensure_ascii=False, indent=0) + ';\n'
open(OUT, 'w').write(out)
print(f'wrote {OUT}: {len(clauses)} clauses, {len(parts)} parts, {len(cap_parts)} capability parts, law-table rows: {len(law)}')
if missing or extra: sys.exit(2)
